name: Service CI

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bootJar
    - name: Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "idawud/turntablapigateway"
        TAG_NAME: "latest"
        LATEST: "true"
    - name: OPEN SSH Private Key
      uses: fifsky/ssh-action@master
      with:
        command: | 
          cd Services-Registery
          echo -e "test" > test.txt
          echo -e ${{ secrets.ENV }} > .envs/.${{ secrets.SERVICE }}
          sudo docker-compose stop ${{ secrets.SERVICE }}
          sudo docker-compose rm -f -v ${{ secrets.SERVICE }}
          sudo docker-compose pull ${{ secrets.SERVICE }}
          sudo docker-compose up -d --force-recreate --no-deps --build ${{ secrets.SERVICE }}
          sudo docker-compose start ${{ secrets.SERVICE }}
        host: ${{ secrets.EC2_HOST }}
        user: ubuntu
        key: ${{ secrets.EC2}}
        args: "-tt -vvv"